:toc: macro

= Bootstrap Project

Module description

:icons: font
:numbered:
toc::[]

== Usage

```
locals {
  labels {
    contact     = "author@email.co"
    environment = "fancy-dev"
    vertical    = "fancy"
  }
}

module "fancy_google_project" {
  source                = "git@github.com:thesis/terraform-google-bootstrap-project.git"
  project_name          = "fancy-dev"
  org_id                = "xxxyyyzzz"
  billing_account       = "111222333"
  project_owner_members = ["john@email.co", "lilly@email.co",]
  location              = "us-central1"
  labels                = ${local.labels}
}

```

== Inputs (Required)

Table of available module inputs in the format:

[%header,cols=5*]
|===
|`Name`
|Description
|Type
|Default
|Required

|`project_name`
|The name for your Google project.
|string
| `""`
|yes

|`org_id`
|The Google organization ID that the project will be assigned to.
|string
| `""`
|yes

|`billing_account`
|The Google billing account that project charges will be assigned to.
|list
| `""`
|yes

|`project_owner_members`
|List of administrators who will be given IAM role `owner` for the project.
|list
| `[]`
|yes

|`location`
|The area where your bucket will be deployed.
|string
| `"us-east4"`
|yes
|===

== Notes (Optional)

For a Thesis or a Thesis vertical project this should be the first module you run.
It does require admin access on the GCP Organization level.

== License (Required)

Copyright Card For Coin Inc., D.B.A Thesis, 2019
